server:
  shutdown: graceful
  tomcat:
    connection-timeout: 5s
  servlet:
    session:
      cookie:
        name: CLOUD_STORAGE_SESSION
spring:
  application:
    name: cloud-storage
  datasource:
    url: jdbc:postgresql://localhost:5430/cloud_storage_dev_db
    username: test-user
    password: test-password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 25
      show_sql: true
      format_sql: true
      hbm2ddl.auto: none
    open-in-view: false
  data:
    redis:
      host: localhost
      password: password
      port: 6378
  session:
    timeout: 14d

logging:
  level:
    ua.zhenya.cloudstorage: DEBUG

minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: password
  bucket-name: user-files
