version: '3.8'

services:
  backend:
    image: cloud-storage
    container_name: cloud-storage-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  postgres:
    image: postgres:16.1
    container_name: cloud_postgres
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_USER=${CLOUD_DB_USERNAME}
      - POSTGRES_PASSWORD=${CLOUD_DB_PASSWORD}
      - POSTGRES_DB=${CLOUD_DB_NAME}
      - PGPORT=5431
    volumes:
      - db_storage-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "cloud_storage_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=${CLOUD_REDIS_HOST}
      - REDIS_PASSWORD=${CLOUD_REDIS_PASSWORD}
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${CLOUD_MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${CLOUD_MINIO_PASSWORD}
    command: server /data --console-address ":9001"

  frontend:
    image: cloud_storage_frontend
    container_name: cloud_storage_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  minio-data:
  db_storage-data:
  redis-data:
