version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9090:9090"
      - "9091:9091"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio-data:
