CREATE TABLE users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(20) NOT NULL,
    password varchar(256) NOT NULL,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    constraint username_length CHECK (LENGTH(username) >= 3),
    constraint password_length CHECK (LENGTH(password) >= 8)
);

CREATE UNIQUE INDEX idx_username ON users(username);
